UserSettingsMemberMetaData memberMetaData[] =
{
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, backgroundColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, lineNumColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, cursorColour)},
    {TYPE_COLOUR_RGBA, StructOffset(UserSettings, highlightColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, defaultTextColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, identifierColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, unknownColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, punctuationColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, keywordColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, operatorColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, preprocessorColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, numberColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, boolColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, functionColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, customTypeColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, defineColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, inbuiltTypeColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, stringColour)},
    {TYPE_COLOUR_RGB, StructOffset(UserSettings, commentColour)}
};