struct UserSettings
{
    Colour backgroundColour;
    Colour lineNumColour;
    Colour cursorColour;
    ColourRGBA highlightColour;
    Colour defaultTextColour;
    Colour punctuationColour;
    Colour operatorColour;
    Colour stringColour;
    Colour numberColour;
    Colour boolColour;
    Colour identifierColour;
    Colour functionColour;
    Colour customTypeColour;
    Colour inbuiltTypeColour;
    Colour keywordColour;
    Colour preprocessorColour;
    Colour defineColour;
    Colour commentColour;
    Colour unknownColour;
};